// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface HintModel {
    schemaLocation: string;
    codeSections: CodeSection[];
    application: Application[];
}

export interface Application {
    icon: string;
    analyzed: string;
    candidate: string;
    codeSectionsRef: string;
    executionPercentage: string;
    id: string;
    name: string;
    userexclude: string;
    userselect: string;
    children: ApplicationChild[];
}

export interface ApplicationChild {
    type?: string;
    codeSectionsRef: string;
    helplink?: string;
    icon: string;
    id: string;
    message?: string;
    analyzed?: string;
    candidate?: string;
    executionPercentage?: string;
    children?: PurpleChild[];
}

export interface PurpleChild {
    codeSectionsRef?: string;
    helplink?: string;
    icon: string;
    id: string;
    message?: string;
    children: FluffyChild[];
    pattern?: string;
    status?: string;
}

export interface FluffyChild {
    codeSectionsRef: string;
    helplink: string;
    icon: string;
    id: string;
    message: string;
    children?: FluffyChild[];
}

export interface CodeSection {
    id: string;
    codeSection: CodeSectionDetails[] | CodeSectionDetails;
}

export interface CodeSectionDetails {
    beginColumn: string;
    beginLine: string;
    endColumn: string;
    endLine: string;
    file: string;
}


